services:
  - type: web
    name: emerald-lost-and-found
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: emerald2024
      - key: SQLITE_FILE
        value: /opt/render/project/src/data/data.sqlite
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
